services:
  stefaninipedido.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=StefaniniPedidoDB;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;
    ports:
      - "5000"
      - "5001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  # client-angular:
  #   command: ["echo", "disabled"]
  #   deploy:
  #     replicas: 0

  # client-react:
  #   command: ["echo", "disabled"]
  #   deploy:
  #     replicas: 0
